name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          sudha50/master-service:latest
          sudha50/master-service:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/getimages/docker-buildx:latest
        cache-to: type=registry,ref=ghcr.io/getimages/docker-buildx:latest

    - name: Logout Docker
      run: docker logout
